export const TEAMS = [
  { abbr: 'ARI', name: 'Cardinals', conf: 'NFC', div: 'West', color: '#97233F' },
  { abbr: 'ATL', name: 'Falcons', conf: 'NFC', div: 'South', color: '#A71930' },
  { abbr: 'BAL', name: 'Ravens', conf: 'AFC', div: 'North', color: '#241773' },
  { abbr: 'BUF', name: 'Bills', conf: 'AFC', div: 'East', color: '#00338D' },
  { abbr: 'CAR', name: 'Panthers', conf: 'NFC', div: 'South', color: '#0085CA' },
  { abbr: 'CHI', name: 'Bears', conf: 'NFC', div: 'North', color: '#0B162A' },
  { abbr: 'CIN', name: 'Bengals', conf: 'AFC', div: 'North', color: '#FB4F14' },
  { abbr: 'CLE', name: 'Browns', conf: 'AFC', div: 'North', color: '#8a5a2b' },
  { abbr: 'DAL', name: 'Cowboys', conf: 'NFC', div: 'East', color: '#003594' },
  { abbr: 'DEN', name: 'Broncos', conf: 'AFC', div: 'West', color: '#FB4F14' },
  { abbr: 'DET', name: 'Lions', conf: 'NFC', div: 'North', color: '#0076B6' },
  { abbr: 'GB', name: 'Packers', conf: 'NFC', div: 'North', color: '#203731' },
  { abbr: 'HOU', name: 'Texans', conf: 'AFC', div: 'South', color: '#03202F' },
  { abbr: 'IND', name: 'Colts', conf: 'AFC', div: 'South', color: '#002C5F' },
  { abbr: 'JAX', name: 'Jaguars', conf: 'AFC', div: 'South', color: '#101820' },
  { abbr: 'KC', name: 'Chiefs', conf: 'AFC', div: 'West', color: '#E31837' },
  { abbr: 'LAC', name: 'Chargers', conf: 'AFC', div: 'West', color: '#0080C6' },
  { abbr: 'LAR', name: 'Rams', conf: 'NFC', div: 'West', color: '#003594' },
  { abbr: 'LV', name: 'Raiders', conf: 'AFC', div: 'West', color: '#a5a5a8' },
  { abbr: 'MIA', name: 'Dolphins', conf: 'AFC', div: 'East', color: '#008E97' },
  { abbr: 'MIN', name: 'Vikings', conf: 'NFC', div: 'North', color: '#4F2683' },
  { abbr: 'NE', name: 'Patriots', conf: 'AFC', div: 'East', color: '#002244' },
  { abbr: 'NO', name: 'Saints', conf: 'NFC', div: 'South', color: '#D3BC8D' },
  { abbr: 'NYG', name: 'Giants', conf: 'NFC', div: 'East', color: '#0B2265' },
  { abbr: 'NYJ', name: 'Jets', conf: 'AFC', div: 'East', color: '#125740' },
  { abbr: 'PHI', name: 'Eagles', conf: 'NFC', div: 'East', color: '#004C54' },
  { abbr: 'PIT', name: 'Steelers', conf: 'AFC', div: 'North', color: '#FFB612' },
  { abbr: 'SF', name: '49ers', conf: 'NFC', div: 'West', color: '#AA0000' },
  { abbr: 'SEA', name: 'Seahawks', conf: 'NFC', div: 'West', color: '#69BE28' },
  { abbr: 'TB', name: 'Buccaneers', conf: 'NFC', div: 'South', color: '#D50A0A' },
  { abbr: 'TEN', name: 'Titans', conf: 'AFC', div: 'South', color: '#4B92DB' },
  { abbr: 'WAS', name: 'Commanders', conf: 'NFC', div: 'East', color: '#5A1414' },
];

export const TEAM_MAP = Object.fromEntries(TEAMS.map((t) => [t.abbr, t]));
